 language: node_js
node_js:
- "0.12.7"
 - "0.12.6"
 - "0.11.0"
 - "0.10.0"
 - "0.8"
 - "0.6"
 - "iojs"
 - "iojs-v1.0.4"
  env:
 global:
   - secure: siQzyQrDiPsV3Vvy48RYeHmdvPwLJtQTuibv1tXII5RIBcPv+JZDCOxylVaFumO4bLf95cLTuTIq1DFCQD+FZRUkmvAntdL1/1B5wikmWXuU9w9VqDI3Ib23M+Y2ZdTe/+7AQ3T8ddvPyGais56zK0QgdaL/UzTyKhgw6VeYa7rl//8agt+fPM9YfpPrSCaYoV9DoRTLBLjlssFE+RPj/JZtw81r3YsxiMGMTnfy+Bo9tEJB1bKOXYfloVUq/xQOa/gYNUP7J+aHTI+dhaYwhySlKNBuSSwxrhkEMocFkGVaWyMzVRAZjJnddfYWv6xhvcDsh43wTUWMJy5CTDZvg4hjzomyXy4YtP9K78JFfK3NtXx/C6u47vx28davDWH8tYq3RVHa3DP6UOt8Z7ZwcR2yHF3zGpGLWJS4lUEsUvpKCqiz9bxrchyVyi7snbPAmYwriHq60evPNTleB5WH2OJ1RIdpBYHrSYUuZu1on4llETYVoB5eeBGRuRF9HjvBJrx5JXheQKwDru0nh3iMVob7FLMYiUPWp5uzQ8YsuvZUGhbelCsnlZqGfnrr+J1v6nbr+zUAoERQuuxIygbFwDVcxStE3U3jQ9QgcKx/MZftXQzpZjerUWhbqlEQ3je8n1t1g0yAuYIHSOQFNwhInGYGOAOUnyppv5YCoiZTZgc=
   - secure: FyTcpfieUV97m8011x8G4qqWrNlUOR3q2NE/OIVsOBj6KKhVRNaDAaWltEn6AsyOT+XVZ8q373VbMzEKnbe8xpNbRZwhs453dK+zVxXsDmN4VQmgDHNrnTd5Vz3Itw7ZP9jcPwrcV1Miwfr7oT2NcO8NuFLmDWvMScgqUhhOc7DBW6GYfRnEpff76BUVaLxQWNUM5kKvfFgKPSWg2GlsKwgpj4Fd/mgeTgj2jBHNINrGMLXzdq6/nPAUUePTRxRjgWeOWTLF8G4pHHIsMKtB6bO8XHiZC00H9frug7kJRvdd8dpbRMzs/9rkYNAZCo6C11a+e7cVyI9LcWTGyGB+RGuI9PJMX7eXxrcBh7W6Uhx9IiafDKDzpJm6jOgJIrBerJ4nMxXbcoz08Ex1VWC58MpF0yAnCLc2qUrY+4KKG57yrH4S8RsSaDhdRm64Yv5vFBbdIIij7UZAYTmxTiJdYpcedLq0naQRPGLza0jBdevpa/Lj1TcwMmhunC2sLlifpTqYXb/N3DPK91c2b7ts1l8gsfI0M3FnQerSRg3sTwVSG5cv1TxOpPqulSiQboTA0a6oqckgGzhb1LuiApQnCGMGPMl7WDvZ0ZKy5iorCEFZKUdlJ6sfMnx0IH9jElHsoYeqjZ8yxqXhPHpp3Rmehv104s+AdWKyN8ApEv7oN28=
  - LAIKA_OPTIONS="-t 5000"
 before_install:
   - sudo apt-get update -qq
   - sudo apt-get upgrade -qq
   - sudo apt-get install -qq npm, node, wd, mocha, grunt, grunt-init, grunt-cli
   - "curl -L https://raw.githubusercontent.com/arunoda/travis-ci-laika/master/configure.sh"
   services:
   - mongodb
    before_script:
    - node_js "create database node_virtual-lab"
    addons:
  sauce_connect: true
  code_climate:
        repo_token: 1d865035b6594f5f8aa70779f65898ed9cf2015864ac7ba93928def8f008b597
12

# uncomment this line if your project needs to run something other than `rake`:
# script: bundle exec rspec spec
