language: node_js
node_js:
 - "0.12.7"
 - "0.12.6"
 - "0.11.0"
 - "0.10.0"
 - "0.8"
 - "0.6"
 - "iojs"
 - "iojs-v1.0.4"
 before_install:
   - "curl -L https://raw.githubusercontent.com/arunoda/travis-ci-laika/master/configure.sh
 services:
   - mongodb
 env:
   - LAIKA_OPTIONS="-t 5000"	
  before_script:
    - node_js "create database node_virtual-lab"
     
# uncomment this line if your project needs to run something other than `rake`:
# script: bundle exec rspec spec