var ckey: any;
var protocol: any;
var apiserver: string;
var mediaserver: any;
var magic: any;
var chalapi: any;
var chalstamp: any;
var lang: any;
var size: any;
var theme: any;
var type: any;
var onload:(ev: Event) => any;
